name: Build

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:
    # manual run

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: hugo --buildDrafts --gc --verbose --minify

